import React, { createContext, useContext, useState } from "react";

const T = {
  en: {
    appName: "AgriSense",
    tagline: "Smart Crop Intelligence for Indian Farmers",
    home: "Home",
    analyze: "Analyze Crop",
    simulator: "Simulator",
    map: "Market Map",
    market: "Market Prices",
    pestRisk: "Pest Risk",
    uploadImage: "Upload Image",
    capturePhoto: "Capture Photo",
    dropImage: "Drop image here or click to browse",
    analyzing: "Analyzing…",
    analyze_btn: "Analyze Crop",
    cropType: "Crop Type",
    freshness: "Freshness",
    confidence: "Confidence",
    spoilageDays: "Spoilage in",
    days: "days",
    pestDetected: "Pest Detected",
    diseaseDetected: "Disease Detected",
    recommendations: "Recommendations",
    temperature: "Temperature (°C)",
    humidity: "Humidity (%)",
    storageType: "Storage Type",
    room: "Room Temp",
    cold: "Cold Storage",
    freezer: "Freezer",
    controlled: "Controlled Atm.",
    simulate: "Simulate",
    simulating: "Simulating…",
    updatedSpoilage: "Updated Spoilage Estimate",
    nearbyMandis: "Nearby Mandis",
    coldStorage: "Cold Storage",
    priceChart: "Price Forecast (14 days)",
    bestSellTime: "Best Sell Time",
    currentPrice: "Current Price",
    selectCrop: "Select Crop",
    riskLevel: "Risk Level",
    pestProbability: "Pest Probability",
    pestTypes: "Potential Pests",
    noImage: "Please upload or capture an image first",
    offline: "You are offline — showing cached data",
    fileLimit: "Max 10 MB · JPG, PNG, WebP",
    features_title: "What can AgriSense do?",
    how_it_works: "How It Works",
    step1_title: "Upload Photo",
    step1_desc: "Take a photo or upload from gallery",
    step2_title: "AI Analysis",
    step2_desc: "ML model identifies crop & freshness",
    step3_title: "Get Recommendations",
    step3_desc: "Storage tips, market prices & more",
    feature_crop_title: "Crop Analysis",
    feature_crop_desc:
      "Instantly identify crop type, freshness & spoilage timeline from a single photo.",
    feature_simulator_title: "What-If Simulator",
    feature_simulator_desc:
      "Adjust temperature, humidity & storage type to model exactly how shelf life changes.",
    feature_map_title: "Market Map",
    feature_map_desc:
      "Locate nearby mandis and cold storage facilities on an interactive map.",
    feature_price_title: "Price Forecast",
    feature_price_desc:
      "14-day AI price predictions to help you decide the perfect day to sell.",
    feature_pest_title: "Pest Risk Alerts",
    feature_pest_desc:
      "Real-time pest probability scores based on local weather conditions.",
    crop_tomato: "Tomato",
    crop_potato: "Potato",
    crop_mango: "Mango",
    crop_onion: "Onion",
    crop_wheat: "Wheat",
    crop_rice: "Rice",
    freshness_fresh: "Fresh",
    freshness_moderate: "Moderate",
    freshness_spoiled: "Spoiled",
    tab_all: "📍 All",
    tab_mandi: "🏪 Mandis",
    tab_cold_storage: "❄️ Cold Storage",
  },
  hi: {
    appName: "एग्रीसेंस",
    tagline: "भारतीय किसानों के लिए स्मार्ट फसल विश्लेषण",
    home: "होम",
    analyze: "फसल विश्लेषण",
    simulator: "सिमुलेटर",
    map: "बाज़ार मानचित्र",
    market: "बाज़ार भाव",
    pestRisk: "कीट जोखिम",
    uploadImage: "छवि अपलोड करें",
    capturePhoto: "फोटो लें",
    dropImage: "यहाँ छवि खींचें या ब्राउज़ करें",
    analyzing: "विश्लेषण हो रहा है…",
    analyze_btn: "फसल विश्लेषण करें",
    cropType: "फसल प्रकार",
    freshness: "ताजगी",
    confidence: "विश्वास स्कोर",
    spoilageDays: "खराब होने में",
    days: "दिन",
    pestDetected: "कीट मिला",
    diseaseDetected: "रोग मिला",
    recommendations: "सुझाव",
    temperature: "तापमान (°C)",
    humidity: "आर्द्रता (%)",
    storageType: "भंडारण प्रकार",
    room: "सामान्य तापमान",
    cold: "शीत भंडार",
    freezer: "फ्रीजर",
    controlled: "नियंत्रित वातावरण",
    simulate: "सिमुलेट करें",
    simulating: "सिमुलेट हो रहा है…",
    updatedSpoilage: "अनुमानित खराबी",
    nearbyMandis: "नजदीकी मंडियाँ",
    coldStorage: "शीत भंडारण",
    priceChart: "मूल्य पूर्वानुमान (14 दिन)",
    bestSellTime: "बेचने का सबसे अच्छा समय",
    currentPrice: "वर्तमान भाव",
    selectCrop: "फसल चुनें",
    riskLevel: "जोखिम स्तर",
    pestProbability: "कीट संभावना",
    pestTypes: "संभावित कीट",
    noImage: "कृपया पहले एक छवि अपलोड या कैप्चर करें",
    offline: "आप ऑफलाइन हैं — कैश डेटा दिखाया जा रहा है",
    fileLimit: "अधिकतम 10 MB · JPG, PNG, WebP",
    features_title: "एग्रीसेंस क्या कर सकता है?",
    how_it_works: "यह कैसे काम करता है",
    step1_title: "फोटो अपलोड करें",
    step1_desc: "कैमरा से फोटो लें या गैलरी से अपलोड करें",
    step2_title: "AI विश्लेषण",
    step2_desc: "मॉडल फसल और ताजगी पहचानता है",
    step3_title: "सुझाव प्राप्त करें",
    step3_desc: "स्टोरेज टिप्स, बाजार कीमतें और अधिक",
    feature_crop_title: "फसल विश्लेषण",
    feature_crop_desc:
      "एक फोटो से फसल का प्रकार, ताजगी और खराब होने का समय तुरंत जानें।",
    feature_simulator_title: "What-If सिमुलेटर",
    feature_simulator_desc:
      "तापमान, नमी और स्टोरेज बदलकर शेल्फ लाइफ पर असर देखें।",
    feature_map_title: "मार्केट मैप",
    feature_map_desc: "नजदीकी मंडी और कोल्ड स्टोरेज खोजें।",
    feature_price_title: "कीमत पूर्वानुमान",
    feature_price_desc: "14 दिनों की AI आधारित कीमत भविष्यवाणी।",
    feature_pest_title: "कीट जोखिम अलर्ट",
    feature_pest_desc: "मौसम के आधार पर कीट जोखिम की जानकारी।",
    crop_tomato: "टमाटर",
    crop_potato: "आलू",
    crop_mango: "आम",
    crop_onion: "प्याज",
    crop_wheat: "गेहूं",
    crop_rice: "चावल",
    freshness_fresh: "ताज़ा",
    freshness_moderate: "मध्यम",
    freshness_spoiled: "खराब",
    tab_all: "📍 सभी",
    tab_mandi: "🏪 मंडी",
    tab_cold_storage: "❄️ कोल्ड स्टोरेज",
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(
    localStorage.getItem("agrisense_lang") || "en",
  );
  const t = (key) => T[lang][key] ?? key;
  const toggle = () => {
    const next = lang === "en" ? "hi" : "en";
    setLang(next);
    localStorage.setItem("agrisense_lang", next);
  };
  return (
    <LanguageContext.Provider value={{ lang, t, toggle }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
